import { Product, Company, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'content', name: 'Content Generation', subCategories: ['Text', 'Image', 'Video', 'Audio', 'Code'] },
  { id: 'data', name: 'Data Analysis', subCategories: ['Business Intelligence', 'Visualization', 'Predictive'] },
  { id: 'dev', name: 'Development', subCategories: ['LLMs', 'APIs', 'Fine-tuning', 'Deployment'] },
  { id: 'productivity', name: 'Productivity', subCategories: ['Writing Assistant', 'Meeting Notes', 'Email'] },
  { id: 'marketing', name: 'Marketing', subCategories: ['SEO', 'Copywriting', 'Social Media'] },
];

export const COMPANIES: Company[] = [
  { id: 'openai', name: 'OpenAI', valuation: '$80B+', founded: '2015', location: 'San Francisco, CA' },
  { id: 'google', name: 'Google', valuation: '$1.7T', founded: '1998', location: 'Mountain View, CA', parentCompanyId: 'alphabet' },
  { id: 'anthropic', name: 'Anthropic', valuation: '$18B', founded: '2021', location: 'San Francisco, CA' },
  { id: 'midjourney', name: 'Midjourney', valuation: '$10B (Est)', founded: '2022', location: 'San Francisco, CA' },
  { id: 'elevenlabs', name: 'ElevenLabs', valuation: '$1.1B', founded: '2022', location: 'New York, NY' },
  { id: 'microsoft', name: 'Microsoft', valuation: '$3T', founded: '1975', location: 'Redmond, WA' },
  { id: 'suno', name: 'Suno', valuation: '$500M', founded: '2023', location: 'Cambridge, MA' },
  { id: 'jasper', name: 'Jasper', valuation: '$1.5B', founded: '2021', location: 'Austin, TX' },
];

// Helper to generate consistent avatar URLs
const getLogo = (name: string, bg: string = '0ea5e9') => 
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff&size=200&font-size=0.4&bold=true`;

export const PRODUCTS: Product[] = [
  // --- CONTENT: TEXT ---
  {
    id: 'gpt4',
    name: 'ChatGPT (GPT-4)',
    companyId: 'openai',
    logoUrl: getLogo('ChatGPT', '10a37f'),
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'A conversational AI model capable of understanding and generating natural language code, and more.',
    features: ['Multi-modal capabilities', 'Code generation', 'Data analysis', 'Web browsing'],
    website: 'https://chat.openai.com',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2023-03-14',
    lastUpdate: '2024-05-13',
    metrics: { totalUsers: 180000000, mau: 100000000, rating: 4.8, growthRate: 15 },
    tags: ['LLM', 'Chatbot', 'API Available']
  },
  {
    id: 'gemini',
    name: 'Gemini',
    companyId: 'google',
    logoUrl: getLogo('Gemini', '4285F4'),
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'Google’s most capable and general model, built to be multimodal from the ground up.',
    features: ['Native Multimodal', 'Large Context Window', 'Integration with Workspace'],
    website: 'https://gemini.google.com',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2023-12-06',
    lastUpdate: '2024-02-15',
    metrics: { totalUsers: 150000000, mau: 80000000, rating: 4.7, growthRate: 25 },
    tags: ['LLM', 'Multimodal', 'Google']
  },
  {
    id: 'claude3',
    name: 'Claude 3',
    companyId: 'anthropic',
    logoUrl: getLogo('Claude', 'D97757'),
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'A family of foundational AI models that sets new industry benchmarks on a wide range of cognitive tasks.',
    features: ['200K Context Window', 'Strong Reasoning', 'Steerability', 'Reduced Hallucinations'],
    website: 'https://claude.ai',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2024-03-04',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 25000000, mau: 10000000, rating: 4.8, growthRate: 40 },
    tags: ['LLM', 'Safety Focused', 'API Available']
  },

  // --- CONTENT: IMAGE ---
  {
    id: 'midjourney-v6',
    name: 'Midjourney',
    companyId: 'midjourney',
    logoUrl: getLogo('Midjourney', '000000'),
    category: 'Content Generation',
    subCategory: 'Image',
    description: 'An independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    features: ['High Fidelity Images', 'Prompt Adherence', 'Text Rendering', 'Discord Interface'],
    website: 'https://midjourney.com',
    pricing: ['Paid'],
    launchDate: '2023-12-21',
    lastUpdate: '2024-01-15',
    metrics: { totalUsers: 16000000, mau: 5000000, rating: 4.9, growthRate: 10 },
    tags: ['Image Gen', 'Art', 'Discord']
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion',
    companyId: 'stability',
    logoUrl: getLogo('Stability', '2A0944'),
    category: 'Content Generation',
    subCategory: 'Image',
    description: 'Latest open weights image generation model offering better photorealism.',
    features: ['Open Source Weights', 'High Resolution', 'Inpainting', 'Fine-tunable'],
    website: 'https://stability.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-07-26',
    lastUpdate: '2024-04-10',
    metrics: { totalUsers: 10000000, mau: 2000000, rating: 4.7, growthRate: 12 },
    tags: ['Open Source', 'Image Gen']
  },

  // --- CONTENT: VIDEO ---
  {
    id: 'runway-gen2',
    name: 'Runway Gen-2',
    companyId: 'runway',
    logoUrl: getLogo('Runway', '000000'),
    category: 'Content Generation',
    subCategory: 'Video',
    description: 'A multi-modal AI system that can generate novel videos with text, images, or video clips.',
    features: ['Text to Video', 'Image to Video', 'Motion Brush', 'Style Transfer'],
    website: 'https://runwayml.com',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2023-03-20',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 5000000, mau: 1000000, rating: 4.5, growthRate: 30 },
    tags: ['Video Gen', 'Creative Tools']
  },
  {
    id: 'pika-labs',
    name: 'Pika',
    companyId: 'pika-labs',
    logoUrl: getLogo('Pika', 'FF4500'),
    category: 'Content Generation',
    subCategory: 'Video',
    description: 'An idea-to-video platform that brings your creativity to motion.',
    features: ['Text to Video', 'Lip Sync', 'Sound Effects', 'Discord Integration'],
    website: 'https://pika.art',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2023-11-28',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 2000000, mau: 800000, rating: 4.6, growthRate: 50 },
    tags: ['Video', 'Animation']
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    companyId: 'heygen',
    logoUrl: getLogo('HeyGen', '7A28CB'),
    category: 'Content Generation',
    subCategory: 'Video',
    description: 'AI video generation platform for creating business videos with diverse avatars and voices.',
    features: ['AI Avatars', 'Voice Cloning', 'Video Translation', 'Templates'],
    website: 'https://www.heygen.com',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2022-07-01',
    lastUpdate: '2024-04-15',
    metrics: { totalUsers: 1500000, mau: 500000, rating: 4.7, growthRate: 40 },
    tags: ['Business', 'Marketing', 'Avatars']
  },

  // --- CONTENT: AUDIO ---
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    companyId: 'elevenlabs',
    logoUrl: getLogo('ElevenLabs', '000000'),
    category: 'Content Generation',
    subCategory: 'Audio',
    description: 'The most realistic AI text-to-speech and voice cloning software.',
    features: ['Voice Cloning', 'Text to Speech', 'Dubbing', 'API'],
    website: 'https://elevenlabs.io',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2022-08-01',
    lastUpdate: '2024-05-15',
    metrics: { totalUsers: 5000000, mau: 1500000, rating: 4.8, growthRate: 150 },
    tags: ['Voice', 'Audio', 'TTS']
  },
  {
    id: 'suno',
    name: 'Suno',
    companyId: 'suno',
    logoUrl: getLogo('Suno', '000000'),
    category: 'Content Generation',
    subCategory: 'Audio',
    description: 'Make a song about anything. Suno builds a future where anyone can make great music.',
    features: ['Text to Song', 'Instrumental', 'Lyrics Generation', 'Discord Integration'],
    website: 'https://suno.com',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-12-01',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 12000000, mau: 4000000, rating: 4.7, growthRate: 200 },
    tags: ['Music', 'Audio', 'Creative']
  },
  {
    id: 'udio',
    name: 'Udio',
    companyId: 'udio',
    logoUrl: getLogo('Udio', 'FF0055'),
    category: 'Content Generation',
    subCategory: 'Audio',
    description: 'A music creation app that lets anyone generate amazing music in seconds.',
    features: ['High Fidelity Music', 'Genre Mixing', 'Extending Tracks', 'Community'],
    website: 'https://www.udio.com',
    pricing: ['Free', 'Paid'],
    launchDate: '2024-04-10',
    lastUpdate: '2024-05-01',
    metrics: { totalUsers: 5000000, mau: 2000000, rating: 4.6, growthRate: 300 },
    tags: ['Music', 'GenAI']
  },
  {
    id: 'murf-ai',
    name: 'Murf.ai',
    companyId: 'murf',
    logoUrl: getLogo('Murf', 'D92C7F'),
    category: 'Content Generation',
    subCategory: 'Audio',
    description: 'Go from text to speech with a versatile AI voice generator.',
    features: ['Studio Editor', '120+ Voices', 'Sync with Video', 'Canva Integration'],
    website: 'https://murf.ai',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2020-10-01',
    lastUpdate: '2024-02-01',
    metrics: { totalUsers: 1000000, mau: 300000, rating: 4.5, growthRate: 15 },
    tags: ['Voiceover', 'Business']
  },

  // --- CONTENT: CODE ---
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    companyId: 'microsoft',
    logoUrl: getLogo('Copilot', '000000'),
    category: 'Content Generation',
    subCategory: 'Code',
    description: 'Your AI pair programmer. Copilot turns natural language prompts into coding suggestions.',
    features: ['Code Autocomplete', 'Chat Integration in IDE', 'Test Generation', 'Code Explanation'],
    website: 'https://github.com/features/copilot',
    pricing: ['Paid', 'Enterprise'],
    launchDate: '2021-06-29',
    lastUpdate: '2024-02-01',
    metrics: { totalUsers: 10000000, mau: 3000000, rating: 4.6, growthRate: 20 },
    tags: ['Coding', 'Productivity', 'VS Code']
  },
  {
    id: 'cursor',
    name: 'Cursor',
    companyId: 'anysphere',
    logoUrl: getLogo('Cursor', '000000'),
    category: 'Content Generation',
    subCategory: 'Code',
    description: 'The AI-first code editor. Built to make you extraordinarily productive.',
    features: ['Built-in AI', 'Privacy Mode', 'Codebase Indexing', 'VS Code Fork'],
    website: 'https://cursor.sh',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-01-01',
    lastUpdate: '2024-05-01',
    metrics: { totalUsers: 500000, mau: 200000, rating: 4.9, growthRate: 300 },
    tags: ['Editor', 'Coding', 'Developer Tools']
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    companyId: 'tabnine',
    logoUrl: getLogo('Tabnine', '1E40AF'),
    category: 'Content Generation',
    subCategory: 'Code',
    description: 'AI assistant for software developers. Privacy-centric and adaptable to your codebase.',
    features: ['Whole Line Completion', 'Privacy Focused', 'Self-hosted Option', 'Support for 25+ Languages'],
    website: 'https://www.tabnine.com',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2019-01-01',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 1000000, mau: 300000, rating: 4.4, growthRate: 10 },
    tags: ['Coding', 'Enterprise']
  },
  {
    id: 'replit-ghostwriter',
    name: 'Replit AI',
    companyId: 'replit',
    logoUrl: getLogo('Replit', 'F26207'),
    category: 'Content Generation',
    subCategory: 'Code',
    description: 'An AI pair programmer integrated directly into the Replit online IDE.',
    features: ['Complete Code', 'Explain Code', 'Generate Code', 'Browser Based'],
    website: 'https://replit.com/ai',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2022-09-01',
    lastUpdate: '2024-02-01',
    metrics: { totalUsers: 20000000, mau: 5000000, rating: 4.5, growthRate: 25 },
    tags: ['IDE', 'Cloud', 'Education']
  },

  // --- PRODUCTIVITY: MEETING NOTES ---
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    companyId: 'otter',
    logoUrl: getLogo('Otter', '3B82F6'),
    category: 'Productivity',
    subCategory: 'Meeting Notes',
    description: 'AI meeting assistant that records audio, writes notes, captures slides, and generates summaries.',
    features: ['Real-time Transcription', 'Automated Summaries', 'Zoom/Meet Integration', 'Chat with Notes'],
    website: 'https://otter.ai',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2016-01-01',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 10000000, mau: 3000000, rating: 4.6, growthRate: 15 },
    tags: ['Meetings', 'Transcription']
  },
  {
    id: 'fireflies-ai',
    name: 'Fireflies.ai',
    companyId: 'fireflies',
    logoUrl: getLogo('Fireflies', '101828'),
    category: 'Productivity',
    subCategory: 'Meeting Notes',
    description: 'Automate your meeting notes. Fireflies records, transcribes, and analyzes meetings.',
    features: ['Video Conferencing Bot', 'Searchable Transcripts', 'AI Summaries', 'CRM Integration'],
    website: 'https://fireflies.ai',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2016-01-01',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 500000, mau: 150000, rating: 4.7, growthRate: 20 },
    tags: ['Business', 'Productivity']
  },
  {
    id: 'supernormal',
    name: 'Supernormal',
    companyId: 'supernormal',
    logoUrl: getLogo('Supernormal', '059669'),
    category: 'Productivity',
    subCategory: 'Meeting Notes',
    description: 'The AI notetaker for Google Meet and Zoom. Captures meeting details automatically.',
    features: ['Automatic Notes', 'Multi-language', 'Instant Sharing', 'Action Items'],
    website: 'https://supernormal.com',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2021-01-01',
    lastUpdate: '2024-02-01',
    metrics: { totalUsers: 200000, mau: 80000, rating: 4.8, growthRate: 40 },
    tags: ['Remote Work', 'Notes']
  },

  // --- PRODUCTIVITY: WRITING ---
  {
    id: 'grammarly-go',
    name: 'Grammarly',
    companyId: 'grammarly',
    logoUrl: getLogo('Grammarly', '15C39A'),
    category: 'Productivity',
    subCategory: 'Writing Assistant',
    description: 'AI writing assistance that helps you write consistently, clearly, and correctly.',
    features: ['Grammar Checking', 'Tone Detection', 'Generative AI', 'Plagiarism Checker'],
    website: 'https://www.grammarly.com',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2009-07-01',
    lastUpdate: '2024-05-01',
    metrics: { totalUsers: 30000000, mau: 15000000, rating: 4.7, growthRate: 10 },
    tags: ['Writing', 'Editing', 'Education']
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    companyId: 'notion',
    logoUrl: getLogo('Notion', '000000'),
    category: 'Productivity',
    subCategory: 'Writing Assistant',
    description: 'Access the limitless power of AI, right inside Notion. Work faster. Write better. Think bigger.',
    features: ['Summarization', 'Translation', 'Brainstorming', 'Draft Generation'],
    website: 'https://www.notion.so/product/ai',
    pricing: ['Paid'],
    launchDate: '2023-02-22',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 35000000, mau: 10000000, rating: 4.8, growthRate: 25 },
    tags: ['Productivity', 'Workspace']
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    companyId: 'copyai',
    logoUrl: getLogo('Copy.ai', '222222'),
    category: 'Marketing',
    subCategory: 'Copywriting',
    description: 'Generates high-quality copy for your business using advanced AI language models.',
    features: ['Blog Content', 'Digital Ad Copy', 'Social Media Posts', 'Email Marketing'],
    website: 'https://www.copy.ai',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2020-10-01',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 10000000, mau: 2000000, rating: 4.5, growthRate: 15 },
    tags: ['Marketing', 'Writing']
  },
  {
    id: 'jasper-ai',
    name: 'Jasper',
    companyId: 'jasper',
    logoUrl: getLogo('Jasper', '7E56D8'),
    category: 'Marketing',
    subCategory: 'Copywriting',
    description: 'AI copilot for enterprise marketing teams to create on-brand content faster.',
    features: ['Brand Voice', 'Marketing Templates', 'SEO Mode', 'Campaign Management'],
    website: 'https://jasper.ai',
    pricing: ['Paid', 'Enterprise'],
    launchDate: '2021-01-15',
    lastUpdate: '2024-02-20',
    metrics: { totalUsers: 2000000, mau: 500000, rating: 4.4, growthRate: 5 },
    tags: ['Marketing', 'Writing', 'Business']
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    companyId: 'perplexity',
    logoUrl: getLogo('Perplexity', '115e59'),
    category: 'Productivity',
    subCategory: 'Writing Assistant',
    description: 'An AI-powered answer engine that cites sources and provides real-time information.',
    features: ['Real-time Search', 'Citations', 'File Upload Analysis', 'Pro Search'],
    website: 'https://perplexity.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2022-12-01',
    lastUpdate: '2024-05-01',
    metrics: { totalUsers: 10000000, mau: 4000000, rating: 4.8, growthRate: 150 },
    tags: ['Search', 'Research', 'Citations']
  }
];