import { Product, Company, Category } from './types';

// Reconciled Categories based on the provided JSON file, grouped into logical Parents
export const CATEGORIES: Category[] = [
  { 
    id: 'productivity_assistants', 
    name: 'Productivity & Assistants', 
    subCategories: ['AI Assistant', 'Productivity', 'Chatbot', 'Conversational AI', 'Project Management', 'Education'] 
  },
  { 
    id: 'content_creative', 
    name: 'Content & Creative', 
    subCategories: ['Content Creation', 'Image Generation', 'Image Editing', 'Video Editing', 'Generative Video', 'Text-To-Speech'] 
  },
  { 
    id: 'business_ops', 
    name: 'Business & Operations', 
    subCategories: ['Business', 'Marketing', 'Sales', 'E-commerce', 'SEO', 'Customer Support', 'Finance'] 
  },
  { 
    id: 'dev_data', 
    name: 'Development & Data', 
    subCategories: ['Website Builder', 'No-Code', 'Data Analytics', 'Data Management', 'Automation'] 
  },
  { 
    id: 'lifestyle_industry', 
    name: 'Lifestyle & Specific', 
    subCategories: ['Healthcare', 'Travel', 'Social Media', 'Other'] 
  }
];

export const COMPANIES: Company[] = [
  { id: 'anthropic', name: 'Anthropic', valuation: '$18B', founded: '2021', location: 'San Francisco, CA' },
  { id: 'writesonic', name: 'Writesonic', location: 'San Francisco, CA' },
  { id: 'jasper', name: 'Jasper', valuation: '$1.5B', location: 'Austin, TX' },
  { id: 'openai', name: 'OpenAI', valuation: '$80B+', founded: '2015', location: 'San Francisco, CA' },
  { id: 'midjourney', name: 'Midjourney', valuation: '$10B', founded: '2022', location: 'San Francisco, CA' },
  { id: 'google', name: 'Google', valuation: '$1.7T', location: 'Mountain View, CA' },
  { id: 'adobe', name: 'Adobe', valuation: '$200B', location: 'San Jose, CA' },
  { id: 'microsoft', name: 'Microsoft', valuation: '$3T', location: 'Redmond, WA' },
];

// Helper for consistent branding
const getLogo = (name: string, bg: string = '0ea5e9') => 
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff&size=200&font-size=0.4&bold=true`;

// INITIAL SEED DATA (High Quality, Manually Curated)
const SEED_PRODUCTS: Product[] = [
  {
    id: 'claude',
    name: 'Claude 3.5',
    companyId: 'anthropic',
    logoUrl: getLogo('Claude', 'D97757'),
    category: 'Productivity & Assistants',
    subCategory: 'AI Assistant',
    description: 'The industry-leading AI assistant for work, capable of complex reasoning, coding, and writing with a massive context window.',
    features: ['Large Context Window', 'Coding', 'Writing', 'Analysis'],
    website: 'https://claude.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2024-06-20',
    lastUpdate: '2025-12-01',
    metrics: { totalUsers: 25000000, rating: 5, growthRate: 45 },
    tags: ['AI Assistant', 'LLM']
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    companyId: 'openai',
    logoUrl: getLogo('ChatGPT', '10a37f'),
    category: 'Productivity & Assistants',
    subCategory: 'Chatbot',
    description: 'The world\'s most popular conversational AI, featuring voice mode, web browsing, and DALL-E 3 integration.',
    features: ['Voice Mode', 'Web Browsing', 'Image Gen', 'Custom GPTs'],
    website: 'https://chat.openai.com',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2022-11-30',
    lastUpdate: '2025-01-10',
    metrics: { totalUsers: 180000000, rating: 4.8, growthRate: 15 },
    tags: ['Chatbot', 'LLM', 'Standard']
  },
  {
    id: 'gemini',
    name: 'Gemini',
    companyId: 'google',
    logoUrl: getLogo('Gemini', '4285F4'),
    category: 'Productivity & Assistants',
    subCategory: 'Chatbot',
    description: 'Google’s most capable and general model, built to be multimodal from the ground up and integrated with Workspace.',
    features: ['Multimodal', 'Google Workspace', 'Large Context', 'Code'],
    website: 'https://gemini.google.com',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-12-06',
    lastUpdate: '2025-02-15',
    metrics: { totalUsers: 100000000, rating: 4.7, growthRate: 25 },
    tags: ['Chatbot', 'Google']
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    companyId: 'perplexity',
    logoUrl: getLogo('Perplexity', '115e59'),
    category: 'Productivity & Assistants',
    subCategory: 'Conversational AI',
    description: 'An AI-powered answer engine that cites sources and provides real-time information from the web.',
    features: ['Citations', 'Real-time Search', 'Pro Search', 'File Upload'],
    website: 'https://perplexity.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2022-12-01',
    lastUpdate: '2025-01-20',
    metrics: { totalUsers: 15000000, rating: 4.8, growthRate: 120 },
    tags: ['Search', 'Research']
  },
  {
    id: 'character-ai',
    name: 'Character.ai',
    companyId: 'character-ai',
    logoUrl: getLogo('Character', '000'),
    category: 'Productivity & Assistants',
    subCategory: 'Chatbot',
    description: 'Chat with open-ended AI characters that feel alive. Create your own characters or chat with user-created ones.',
    features: ['Persona Creation', 'Roleplay', 'Voice', 'Community'],
    website: 'https://character.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2022-09-01',
    lastUpdate: '2025-03-01',
    metrics: { totalUsers: 20000000, rating: 4.6, growthRate: 60 },
    tags: ['Fun', 'Social']
  },
  {
    id: 'poe',
    name: 'Poe',
    companyId: 'quora',
    logoUrl: getLogo('Poe', 'B91C1C'),
    category: 'Productivity & Assistants',
    subCategory: 'Chatbot',
    description: 'Fast, helpful AI chat. Access the best models from OpenAI, Anthropic, Google, and Meta in one place.',
    features: ['Multi-model Access', 'Bot Creation', 'Monetization'],
    website: 'https://poe.com',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-02-01',
    lastUpdate: '2025-01-01',
    metrics: { totalUsers: 5000000, rating: 4.7, growthRate: 40 },
    tags: ['Aggregator', 'Chatbot']
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    companyId: 'notion',
    logoUrl: getLogo('Notion', '000'),
    category: 'Productivity & Assistants',
    subCategory: 'Productivity',
    description: 'Access the limitless power of AI, right inside Notion. Summarize, write, and extract insights from your notes.',
    features: ['Q&A', 'Autofill', 'Summarization', 'Translation'],
    website: 'https://notion.so',
    pricing: ['Paid'],
    launchDate: '2023-02-22',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 35000000, rating: 4.8, growthRate: 20 },
    tags: ['Workspace', 'Docs']
  },
  {
    id: 'midjourney-v6',
    name: 'Midjourney',
    companyId: 'midjourney',
    logoUrl: getLogo('Midjourney', '000'),
    category: 'Content & Creative',
    subCategory: 'Image Generation',
    description: 'Renowned for the highest aesthetic quality and photorealism in AI image generation.',
    features: ['High Fidelity', 'Discord', 'Art'],
    website: 'https://midjourney.com',
    pricing: ['Paid'],
    launchDate: '2022-07-12',
    lastUpdate: '2025-02-15',
    metrics: { totalUsers: 16000000, rating: 4.9, growthRate: 10 },
    tags: ['Image Generation', 'Art']
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    companyId: 'elevenlabs',
    logoUrl: getLogo('ElevenLabs', '000'),
    category: 'Content & Creative',
    subCategory: 'Text-To-Speech',
    description: 'The standard for natural-sounding AI speech synthesis and voice cloning.',
    features: ['Voice Cloning', 'Dubbing', 'API'],
    website: 'https://elevenlabs.io',
    pricing: ['Freemium'],
    launchDate: '2022-08-01',
    lastUpdate: '2025-05-10',
    metrics: { totalUsers: 5000000, rating: 4.9, growthRate: 120 },
    tags: ['Text-To-Speech', 'Audio']
  },
  {
    id: 'canva',
    name: 'Canva Magic',
    companyId: 'canva',
    logoUrl: getLogo('Canva', '00C4CC'),
    category: 'Content & Creative',
    subCategory: 'Image Editing',
    description: 'A suite of AI tools within Canva. Magic Edit, Magic Eraser, and Magic Design make design accessible to everyone.',
    features: ['Magic Edit', 'Magic Eraser', 'Text to Image', 'Design Gen'],
    website: 'https://canva.com',
    pricing: ['Freemium', 'Paid'],
    launchDate: '2013-01-01',
    lastUpdate: '2025-01-01',
    metrics: { totalUsers: 150000000, rating: 4.8, growthRate: 10 },
    tags: ['Design', 'Mass Market']
  }
];

// DATA IMPORTED AND TRANSFORMED FROM JSON
const IMPORTED_PRODUCTS: Product[] = [
  {
    id: 'scrip-ai',
    name: 'Scrip Ai',
    companyId: 'Scrip',
    logoUrl: getLogo('Scrip Ai'),
    category: 'Content & Creative',
    subCategory: 'Content Creation',
    description: 'Scrip Ai is an AI-Powered Content Creation tool featuring Free Tier and Cloud-Based capabilities.',
    features: ['Free Tier', 'AI-Powered', 'Cloud-Based'],
    website: 'https://scripai.com',
    pricing: ['Freemium'],
    launchDate: '2024-02-06',
    lastUpdate: '2024-04-04',
    metrics: { totalUsers: 39074, rating: 4.3, growthRate: 50 },
    tags: ['Content Creation', 'Cloud-Based']
  },
  {
    id: 'quickads',
    name: 'Quickads',
    companyId: 'Quickads',
    logoUrl: getLogo('Quickads'),
    category: 'Content & Creative',
    subCategory: 'Image Generation',
    description: 'Quickads offers AI-Powered Image generation solutions for creative professionals.',
    features: ['AI-Powered', 'Cloud-Based'],
    website: 'https://www.quickads.ai/',
    pricing: ['Paid'],
    launchDate: '2024-01-17',
    lastUpdate: '2024-06-20',
    metrics: { totalUsers: 41162, rating: 4.7, growthRate: 100 },
    tags: ['Image Generation', 'Marketing']
  },
  {
    id: 'wonderchat',
    name: 'Wonderchat',
    companyId: 'Wonderchat',
    logoUrl: getLogo('Wonderchat'),
    category: 'Productivity & Assistants',
    subCategory: 'Chatbot',
    description: 'Wonderchat is a Customizable, AI-Powered Chatbot solution for businesses.',
    features: ['Customizable', 'AI-Powered', 'Cloud-Based'],
    website: 'https://wonderchat.io',
    pricing: ['Paid'],
    launchDate: '2024-10-07',
    lastUpdate: '2025-02-21',
    metrics: { totalUsers: 92923, rating: 4.7, growthRate: 188 },
    tags: ['Chatbot', 'Support']
  },
  {
    id: 'creatosaurus',
    name: 'Creatosaurus',
    companyId: 'Creatosaurus',
    logoUrl: getLogo('Creatosaurus'),
    category: 'Business & Operations',
    subCategory: 'Marketing',
    description: 'Creatosaurus provides AI-Powered Marketing tools to streamline business operations.',
    features: ['AI-Powered', 'Cloud-Based'],
    website: 'https://www.creatosaurus.io',
    pricing: ['Paid'],
    launchDate: '2022-12-30',
    lastUpdate: '2023-03-29',
    metrics: { totalUsers: 769276, rating: 4.0, growthRate: 95 },
    tags: ['Marketing', 'Social Media']
  },
  {
    id: 'blobr',
    name: 'Blobr',
    companyId: 'Blobr',
    logoUrl: getLogo('Blobr'),
    category: 'Business & Operations',
    subCategory: 'Marketing',
    description: 'Blobr enhances Marketing workflows with AI-Powered capabilities.',
    features: ['AI-Powered', 'Cloud-Based'],
    website: 'https://blobr.io',
    pricing: ['Paid'],
    launchDate: '2024-08-13',
    lastUpdate: '2025-02-21',
    metrics: { totalUsers: 406104, rating: 4.0, growthRate: 89 },
    tags: ['Marketing', 'Integration']
  },
  {
    id: 'pencil',
    name: 'Pencil',
    companyId: 'Pencil',
    logoUrl: getLogo('Pencil'),
    category: 'Business & Operations',
    subCategory: 'Marketing',
    description: 'Pencil generates ads that convert using AI. AI-Powered Marketing platform.',
    features: ['AI-Powered', 'Cloud-Based'],
    website: 'https://trypencil.com',
    pricing: ['Paid'],
    launchDate: '2023-12-14',
    lastUpdate: '2024-07-18',
    metrics: { totalUsers: 505012, rating: 4.8, growthRate: 25 },
    tags: ['Marketing', 'Ads']
  },
  {
    id: 'freeadcopy-com',
    name: 'Freeadcopy',
    companyId: 'Freeadcopy',
    logoUrl: getLogo('Freeadcopy'),
    category: 'Content & Creative',
    subCategory: 'Content Creation',
    description: 'Freeadcopy is an AI-Powered Content Creation tool with a Free Tier.',
    features: ['Free Tier', 'AI-Powered', 'Cloud-Based'],
    website: 'https://freeadcopy.com',
    pricing: ['Freemium'],
    launchDate: '2024-11-13',
    lastUpdate: '2025-02-21',
    metrics: { totalUsers: 36585, rating: 3.5, growthRate: 197 },
    tags: ['Content Creation', 'Copywriting']
  },
  {
    id: 'omneky',
    name: 'Omneky',
    companyId: 'Omneky',
    logoUrl: getLogo('Omneky'),
    category: 'Business & Operations',
    subCategory: 'Marketing',
    description: 'Omneky uses AI to generate and optimize personalized ad creatives at scale.',
    features: ['AI-Powered', 'Cloud-Based'],
    website: 'https://www.omneky.com',
    pricing: ['Paid'],
    launchDate: '2023-12-10',
    lastUpdate: '2024-03-25',
    metrics: { totalUsers: 38693, rating: 4.7, growthRate: 180 },
    tags: ['Marketing', 'Ads']
  },
  {
    "id": "kilo-ai",
    "name": "Kilo Ai",
    "companyId": "Kilo",
    "logoUrl": getLogo("Kilo"),
    "category": "Productivity & Assistants",
    "subCategory": "AI Assistant",
    "description": "Kilo Ai is an AI Assistant designed to boost productivity.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://kilocode.ai",
    "pricing": ["Paid"],
    "launchDate": "2023-01-02",
    "lastUpdate": "2023-04-14",
    "metrics": { "totalUsers": 14272, "rating": 4.1, "growthRate": 29 },
    "tags": ["AI Assistant", "Productivity"]
  },
  {
    "id": "30characters",
    "name": "30Characters",
    "companyId": "30Characters",
    "logoUrl": getLogo("30Characters"),
    "category": "Content & Creative",
    "subCategory": "Content Creation",
    "description": "30Characters helps with Content Creation using AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://30chars.com",
    "pricing": ["Paid"],
    "launchDate": "2022-07-28",
    "lastUpdate": "2023-05-09",
    "metrics": { "totalUsers": 50800, "rating": 4.4, "growthRate": 103 },
    "tags": ["Content Creation"]
  },
  {
    "id": "adbot",
    "name": "Adbot",
    "companyId": "Adbot",
    "logoUrl": getLogo("Adbot"),
    "category": "Business & Operations",
    "subCategory": "Marketing",
    "description": "Your Search Ads Specialist powered by AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://myadbot.com",
    "pricing": ["Paid"],
    "launchDate": "2023-03-19",
    "lastUpdate": "2024-02-17",
    "metrics": { "totalUsers": 5086, "rating": 4.6, "growthRate": 158 },
    "tags": ["Marketing", "Ads"]
  },
  {
    "id": "copycop",
    "name": "Copycop",
    "companyId": "Copycop",
    "logoUrl": getLogo("Copycop"),
    "category": "Content & Creative",
    "subCategory": "Content Creation",
    "description": "AI-Powered Content Creation tool for better copy.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://copycopai.com",
    "pricing": ["Paid"],
    "launchDate": "2022-10-27",
    "lastUpdate": "2023-09-28",
    "metrics": { "totalUsers": 52130, "rating": 4.4, "growthRate": 91 },
    "tags": ["Content Creation"]
  },
  {
    "id": "adinspiration",
    "name": "Adinspiration",
    "companyId": "Adinspiration",
    "logoUrl": getLogo("Adinspiration"),
    "category": "Business & Operations",
    "subCategory": "Marketing",
    "description": "Find marketing inspiration with AI-powered insights.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://adinspiration.com",
    "pricing": ["Paid"],
    "launchDate": "2023-12-05",
    "lastUpdate": "2024-10-25",
    "metrics": { "totalUsers": 78715, "rating": 4.6, "growthRate": 66 },
    "tags": ["Marketing"]
  },
  {
    "id": "engagexai",
    "name": "Engagexai",
    "companyId": "Engagexai",
    "logoUrl": getLogo("Engagexai"),
    "category": "Business & Operations",
    "subCategory": "Marketing",
    "description": "Boost engagement with AI-driven marketing strategies.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://engagexai.com/",
    "pricing": ["Paid"],
    "launchDate": "2024-12-18",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 71128, "rating": 4.2, "growthRate": 143 },
    "tags": ["Marketing"]
  },
  {
    "id": "adcopy-ai",
    "name": "Adcopy Ai",
    "companyId": "Adcopy",
    "logoUrl": getLogo("Adcopy"),
    "category": "Content & Creative",
    "subCategory": "Content Creation",
    "description": "Generate high-converting ad copy with AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://adcopy.ai",
    "pricing": ["Paid"],
    "launchDate": "2023-07-17",
    "lastUpdate": "2024-01-30",
    "metrics": { "totalUsers": 51985, "rating": 4.5, "growthRate": 199 },
    "tags": ["Content Creation", "Ads"]
  },
  {
    "id": "luma-ai",
    "name": "Luma Ai",
    "companyId": "Luma",
    "logoUrl": getLogo("Luma"),
    "category": "Content & Creative",
    "subCategory": "Image Editing",
    "description": "Luma Ai provides advanced AI-Powered Image editing capabilities.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://lumalabs.ai",
    "pricing": ["Paid"],
    "launchDate": "2023-06-19",
    "lastUpdate": "2023-09-01",
    "metrics": { "totalUsers": 16565, "rating": 4.5, "growthRate": 187 },
    "tags": ["Image Editing", "3D"]
  },
  {
    "id": "tripo-ai",
    "name": "Tripo Ai",
    "companyId": "Tripo",
    "logoUrl": getLogo("Tripo"),
    "category": "Content & Creative",
    "subCategory": "Image Generation",
    "description": "Generate 3D assets from text or images instantly.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.tripo3d.ai",
    "pricing": ["Paid"],
    "launchDate": "2023-05-24",
    "lastUpdate": "2023-07-27",
    "metrics": { "totalUsers": 80103, "rating": 3.6, "growthRate": 71 },
    "tags": ["Image Generation", "3D"]
  },
  {
    "id": "meshy",
    "name": "Meshy",
    "companyId": "Meshy",
    "logoUrl": getLogo("Meshy"),
    "category": "Content & Creative",
    "subCategory": "Image Generation",
    "description": "Fast 3D content creation with AI generative mesh technology.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://app.meshy.ai",
    "pricing": ["Paid"],
    "launchDate": "2023-04-14",
    "lastUpdate": "2024-03-18",
    "metrics": { "totalUsers": 74125, "rating": 3.7, "growthRate": 102 },
    "tags": ["Image Generation", "3D"]
  },
  {
    "id": "opus",
    "name": "Opus",
    "companyId": "Opus",
    "logoUrl": getLogo("Opus"),
    "category": "Content & Creative",
    "subCategory": "Video Editing",
    "description": "Opus Clip repurposes long videos into shorts in one click.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://opus.ai",
    "pricing": ["Paid"],
    "launchDate": "2024-07-11",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 23557915, "rating": 4.8, "growthRate": 22 },
    "tags": ["Video Editing", "Shorts"]
  },
  {
    "id": "runcomfy",
    "name": "Runcomfy",
    "companyId": "Runcomfy",
    "logoUrl": getLogo("Runcomfy"),
    "category": "Lifestyle & Specific",
    "subCategory": "Other",
    "description": "Cloud-based ComfyUI workflows for stable diffusion and more.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.runcomfy.com",
    "pricing": ["Paid"],
    "launchDate": "2024-05-07",
    "lastUpdate": "2024-09-07",
    "metrics": { "totalUsers": 33843, "rating": 4.7, "growthRate": 105 },
    "tags": ["Other", "Dev Tools"]
  },
  {
    "id": "nanonets",
    "name": "Nanonets",
    "companyId": "Nanonets",
    "logoUrl": getLogo("Nanonets"),
    "category": "Development & Data",
    "subCategory": "Automation",
    "description": "Automate manual data entry using AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://nanonets.com",
    "pricing": ["Paid"],
    "launchDate": "2023-12-05",
    "lastUpdate": "2024-10-02",
    "metrics": { "totalUsers": 10428, "rating": 4.4, "growthRate": 31 },
    "tags": ["Automation", "OCR"]
  },
  {
    "id": "taxgpt",
    "name": "TaxGPT",
    "companyId": "TaxGPT",
    "logoUrl": getLogo("TaxGPT"),
    "category": "Productivity & Assistants",
    "subCategory": "AI Assistant",
    "description": "Your AI tax assistant for smarter filing and queries.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.taxgpt.com",
    "pricing": ["Paid"],
    "launchDate": "2024-11-25",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 875137, "rating": 3.9, "growthRate": 24 },
    "tags": ["AI Assistant", "Finance"]
  },
  {
    "id": "tango-ai",
    "name": "Tango",
    "companyId": "Tango",
    "logoUrl": getLogo("Tango"),
    "category": "Lifestyle & Specific",
    "subCategory": "Other",
    "description": "Create how-to guides with screenshots automatically.",
    "features": ["Free Tier", "AI-Powered", "Cloud-Based"],
    "website": "https://www.tangoagreements.com",
    "pricing": ["Freemium"],
    "launchDate": "2024-03-20",
    "lastUpdate": "2024-12-30",
    "metrics": { "totalUsers": 37820769, "rating": 4.6, "growthRate": 50 },
    "tags": ["Other", "Documentation"]
  },
  {
    "id": "appzen",
    "name": "Appzen",
    "companyId": "Appzen",
    "logoUrl": getLogo("Appzen"),
    "category": "Business & Operations",
    "subCategory": "Finance",
    "description": "AI for autonomous finance operations.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://appzen.com",
    "pricing": ["Paid"],
    "launchDate": "2022-09-26",
    "lastUpdate": "2023-03-07",
    "metrics": { "totalUsers": 44379, "rating": 3.6, "growthRate": 47 },
    "tags": ["Finance", "Enterprise"]
  },
  {
    "id": "fincheck-by-trezy",
    "name": "Fincheck",
    "companyId": "Trezy",
    "logoUrl": getLogo("Fincheck"),
    "category": "Business & Operations",
    "subCategory": "Finance",
    "description": "Automated financial health checks by Trezy.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://fincheck.trezy.io",
    "pricing": ["Paid"],
    "launchDate": "2024-11-08",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 38402669, "rating": 4.3, "growthRate": 42 },
    "tags": ["Finance"]
  },
  {
    "id": "neuroflash",
    "name": "Neuroflash",
    "companyId": "Neuroflash",
    "logoUrl": getLogo("Neuroflash"),
    "category": "Content & Creative",
    "subCategory": "Image Generation",
    "description": "AI text and image generator for marketing content.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://app.neuro-flash.com/free",
    "pricing": ["Paid"],
    "launchDate": "2023-08-05",
    "lastUpdate": "2024-03-04",
    "metrics": { "totalUsers": 19318, "rating": 3.9, "growthRate": 45 },
    "tags": ["Image Generation", "Copywriting"]
  },
  {
    "id": "sellthetrend",
    "name": "Sellthetrend",
    "companyId": "Sellthetrend",
    "logoUrl": getLogo("Sellthetrend"),
    "category": "Business & Operations",
    "subCategory": "Sales",
    "description": "AI dropshipping product research tool.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.SellTheTrend.com/join/affiliate14309",
    "pricing": ["Paid"],
    "launchDate": "2024-05-10",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 28204017, "rating": 4.3, "growthRate": 26 },
    "tags": ["Sales", "E-commerce"]
  },
  {
    "id": "magical-ai",
    "name": "Magical Ai",
    "companyId": "Magical",
    "logoUrl": getLogo("Magical"),
    "category": "Development & Data",
    "subCategory": "Automation",
    "description": "Automate repetitive tasks with AI in your browser.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.getmagical.com",
    "pricing": ["Paid"],
    "launchDate": "2022-11-13",
    "lastUpdate": "2023-02-23",
    "metrics": { "totalUsers": 29239743, "rating": 4.8, "growthRate": 13 },
    "tags": ["Automation", "Productivity"]
  },
  {
    "id": "v7-lab",
    "name": "V7 Lab",
    "companyId": "V7",
    "logoUrl": getLogo("V7"),
    "category": "Development & Data",
    "subCategory": "Data Analytics",
    "description": "Automated labeling and data management for computer vision.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.v7labs.com",
    "pricing": ["Paid"],
    "launchDate": "2023-05-17",
    "lastUpdate": "2024-04-28",
    "metrics": { "totalUsers": 249185, "rating": 4.7, "growthRate": 64 },
    "tags": ["Data Analytics", "Vision"]
  },
  {
    "id": "sierra",
    "name": "Sierra",
    "companyId": "Sierra",
    "logoUrl": getLogo("Sierra"),
    "category": "Productivity & Assistants",
    "subCategory": "Conversational AI",
    "description": "Conversational AI agents for customer experience.",
    "features": ["Customizable", "AI-Powered", "Cloud-Based"],
    "website": "https://sierra.ai",
    "pricing": ["Paid"],
    "launchDate": "2024-02-09",
    "lastUpdate": "2024-04-12",
    "metrics": { "totalUsers": 968826, "rating": 4.9, "growthRate": 22 },
    "tags": ["Conversational AI", "Enterprise"]
  },
  {
    "id": "openphone",
    "name": "Openphone",
    "companyId": "Openphone",
    "logoUrl": getLogo("Openphone"),
    "category": "Business & Operations",
    "subCategory": "Customer Support",
    "description": "The modern phone system for business with AI capabilities.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.openphone.com",
    "pricing": ["Paid"],
    "launchDate": "2022-05-29",
    "lastUpdate": "2022-07-31",
    "metrics": { "totalUsers": 54162, "rating": 4.5, "growthRate": 117 },
    "tags": ["Customer Support", "Communication"]
  },
  {
    "id": "glean",
    "name": "Glean",
    "companyId": "Glean",
    "logoUrl": getLogo("Glean"),
    "category": "Productivity & Assistants",
    "subCategory": "Productivity",
    "description": "AI-powered work assistant and enterprise search.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.glean.com",
    "pricing": ["Paid"],
    "launchDate": "2023-08-22",
    "lastUpdate": "2023-12-15",
    "metrics": { "totalUsers": 17401, "rating": 3.6, "growthRate": 83 },
    "tags": ["Productivity", "Search"]
  },
  {
    "id": "outreach",
    "name": "Outreach",
    "companyId": "Outreach",
    "logoUrl": getLogo("Outreach"),
    "category": "Business & Operations",
    "subCategory": "Sales",
    "description": "Sales execution platform powered by AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.outreach.io",
    "pricing": ["Paid"],
    "launchDate": "2024-11-25",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 6047, "rating": 3.6, "growthRate": 182 },
    "tags": ["Sales", "Enterprise"]
  },
  {
    "id": "adept",
    "name": "Adept",
    "companyId": "Adept",
    "logoUrl": getLogo("Adept"),
    "category": "Productivity & Assistants",
    "subCategory": "Productivity",
    "description": "An AI teammate that can browse the internet and use software.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.adept.ai",
    "pricing": ["Paid"],
    "launchDate": "2022-08-11",
    "lastUpdate": "2023-05-20",
    "metrics": { "totalUsers": 70397, "rating": 4.7, "growthRate": 128 },
    "tags": ["Productivity", "Agents"]
  },
  {
    "id": "pinecone",
    "name": "Pinecone",
    "companyId": "Pinecone",
    "logoUrl": getLogo("Pinecone"),
    "category": "Development & Data",
    "subCategory": "Data Analytics",
    "description": "Vector database for high-performance AI applications.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://www.pinecone.io",
    "pricing": ["Paid"],
    "launchDate": "2024-12-03",
    "lastUpdate": "2025-02-21",
    "metrics": { "totalUsers": 873863, "rating": 3.7, "growthRate": 63 },
    "tags": ["Data Analytics", "Infrastructure"]
  },
  {
    "id": "writer",
    "name": "Writer",
    "companyId": "Writer",
    "logoUrl": getLogo("Writer"),
    "category": "Content & Creative",
    "subCategory": "Content Creation",
    "description": "Full-stack generative AI platform for enterprises.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://writer.com",
    "pricing": ["Paid"],
    "launchDate": "2022-02-07",
    "lastUpdate": "2022-04-07",
    "metrics": { "totalUsers": 175151, "rating": 3.8, "growthRate": 59 },
    "tags": ["Content Creation", "Enterprise"]
  },
  {
    "id": "deepgram",
    "name": "Deepgram",
    "companyId": "Deepgram",
    "logoUrl": getLogo("Deepgram"),
    "category": "Content & Creative",
    "subCategory": "Text-To-Speech",
    "description": "Speech-to-text API built for enterprise scale.",
    "features": ["API Access", "AI-Powered", "Cloud-Based"],
    "website": "https://deepgram.partnerlinks.io/ps3mjcc1vth7",
    "pricing": ["Paid"],
    "launchDate": "2024-06-24",
    "lastUpdate": "2025-01-17",
    "metrics": { "totalUsers": 99181, "rating": 4.9, "growthRate": 82 },
    "tags": ["Text-To-Speech", "API"]
  },
  {
    "id": "tidio",
    "name": "Tidio",
    "companyId": "Tidio",
    "logoUrl": getLogo("Tidio"),
    "category": "Business & Operations",
    "subCategory": "Customer Support",
    "description": "Customer service platform with AI chatbots.",
    "features": ["Customizable", "AI-Powered", "Cloud-Based"],
    "website": "https://www.tidio.com",
    "pricing": ["Paid"],
    "launchDate": "2023-05-05",
    "lastUpdate": "2024-03-16",
    "metrics": { "totalUsers": 65324, "rating": 4.1, "growthRate": 176 },
    "tags": ["Customer Support", "Chatbot"]
  },
  {
    "id": "voiceflow",
    "name": "Voiceflow",
    "companyId": "Voiceflow",
    "logoUrl": getLogo("Voiceflow"),
    "category": "Productivity & Assistants",
    "subCategory": "Conversational AI",
    "description": "Platform for building AI agents and chatbots.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://voiceflow.com",
    "pricing": ["Paid"],
    "launchDate": "2022-09-30",
    "lastUpdate": "2023-06-29",
    "metrics": { "totalUsers": 68170, "rating": 4.2, "growthRate": 126 },
    "tags": ["Conversational AI", "Builder"]
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "companyId": "Cursor",
    "logoUrl": getLogo("Cursor"),
    "category": "Development & Data",
    "subCategory": "No-Code",
    "description": "The AI code editor built for pair programming.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://cursor.directory",
    "pricing": ["Paid"],
    "launchDate": "2024-02-07",
    "lastUpdate": "2024-12-28",
    "metrics": { "totalUsers": 81680, "rating": 4.9, "growthRate": 51 },
    "tags": ["Development", "Code"]
  },
  {
    "id": "zapier",
    "name": "Zapier",
    "companyId": "Zapier",
    "logoUrl": getLogo("Zapier"),
    "category": "Development & Data",
    "subCategory": "Automation",
    "description": "Automation platform connecting your apps with AI.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://zapier.com",
    "pricing": ["Paid"],
    "launchDate": "2022-08-11",
    "lastUpdate": "2023-04-14",
    "metrics": { "totalUsers": 37707, "rating": 4.8, "growthRate": 17 },
    "tags": ["Automation", "Integration"]
  },
  {
    "id": "otter-ai",
    "name": "Otter.ai",
    "companyId": "Otter",
    "logoUrl": getLogo("Otter"),
    "category": "Productivity & Assistants",
    "subCategory": "AI Assistant",
    "description": "AI meeting assistant for notes and summaries.",
    "features": ["Real-time Processing", "AI-Powered", "Cloud-Based"],
    "website": "https://otter.ai/referrals/X6YW9FRA",
    "pricing": ["Paid"],
    "launchDate": "2023-08-26",
    "lastUpdate": "2024-08-14",
    "metrics": { "totalUsers": 25345, "rating": 4.1, "growthRate": 95 },
    "tags": ["AI Assistant", "Meetings"]
  },
  {
    "id": "intercom",
    "name": "Intercom",
    "companyId": "Intercom",
    "logoUrl": getLogo("Intercom"),
    "category": "Business & Operations",
    "subCategory": "Customer Support",
    "description": "The only AI customer service solution you need.",
    "features": ["Customizable", "AI-Powered", "Cloud-Based"],
    "website": "https://intercom.com",
    "pricing": ["Paid"],
    "launchDate": "2022-01-06",
    "lastUpdate": "2022-10-13",
    "metrics": { "totalUsers": 59715, "rating": 4.2, "growthRate": 123 },
    "tags": ["Customer Support"]
  },
  {
    "id": "scale",
    "name": "Scale AI",
    "companyId": "Scale",
    "logoUrl": getLogo("Scale"),
    "category": "Development & Data",
    "subCategory": "Data Analytics",
    "description": "Data engine for AI applications.",
    "features": ["AI-Powered", "Cloud-Based"],
    "website": "https://scale.com",
    "pricing": ["Paid"],
    "launchDate": "2023-10-06",
    "lastUpdate": "2023-12-19",
    "metrics": { "totalUsers": 790833, "rating": 3.5, "growthRate": 28 },
    "tags": ["Data Analytics", "Infrastructure"]
  },
  {
    "id": "chatbase",
    "name": "Chatbase",
    "companyId": "Chatbase",
    "logoUrl": getLogo("Chatbase"),
    "category": "Productivity & Assistants",
    "subCategory": "Chatbot",
    "description": "Build an AI chatbot trained on your data.",
    "features": ["Customizable", "AI-Powered", "Cloud-Based"],
    "website": "https://www.chatbase.co/",
    "pricing": ["Paid"],
    "launchDate": "2023-11-15",
    "lastUpdate": "2024-01-26",
    "metrics": { "totalUsers": 83582, "rating": 4.5, "growthRate": 91 },
    "tags": ["Chatbot", "No-Code"]
  },
  {
    "name": "HeySam",
    "companyId": "HeySam",
    "category": "Business & Operations",
    "subCategory": "Sales",
    "website": "https://heysam.ai",
    "features": [
      "AI-Powered",
      "Cloud-Based",
      "API Access"
    ],
    "metrics": {
      "totalUsers": 347369,
      "rating": 4.8,
      "growthRate": 73
    },
    "launchDate": "2023-01-01",
    "lastUpdate": "2025-02-21",
    "id": "heysam",
    "logoUrl": "https://ui-avatars.com/api/?name=HeySam&background=0ea5e9&color=fff&size=200&font-size=0.4&bold=true",
    "description": "HeySam is an AI-Powered Sales tool designed to enhance Business & Operations.",
    "pricing": [
      "Paid"
    ],
    "tags": [
      "Sales"
    ]
  }
];

// Combine seed with imported (deduplicated by ID logic in a real app, here checking IDs manually or assuming unique set)
export const PRODUCTS: Product[] = [...SEED_PRODUCTS, ...IMPORTED_PRODUCTS];