import { Product, Company, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'content', name: 'Content Generation', subCategories: ['Text', 'Image', 'Video', 'Audio', 'Code'] },
  { id: 'data', name: 'Data Analysis', subCategories: ['Business Intelligence', 'Visualization', 'Predictive'] },
  { id: 'dev', name: 'Development', subCategories: ['LLMs', 'APIs', 'Fine-tuning', 'Deployment'] },
  { id: 'productivity', name: 'Productivity', subCategories: ['Writing Assistant', 'Meeting Notes', 'Email'] },
  { id: 'marketing', name: 'Marketing', subCategories: ['SEO', 'Copywriting', 'Social Media'] },
];

export const COMPANIES: Company[] = [
  { id: 'openai', name: 'OpenAI', valuation: '$80B+', founded: '2015', location: 'San Francisco, CA' },
  { id: 'google', name: 'Google', valuation: '$1.7T', founded: '1998', location: 'Mountain View, CA', parentCompanyId: 'alphabet' },
  { id: 'anthropic', name: 'Anthropic', valuation: '$18B', founded: '2021', location: 'San Francisco, CA' },
  { id: 'midjourney', name: 'Midjourney', valuation: '$10B (Est)', founded: '2022', location: 'San Francisco, CA' },
  { id: 'stability', name: 'Stability AI', valuation: '$1B', founded: '2020', location: 'London, UK' },
  { id: 'microsoft', name: 'Microsoft', valuation: '$3T', founded: '1975', location: 'Redmond, WA' },
  { id: 'runway', name: 'Runway', valuation: '$1.5B', founded: '2018', location: 'New York, NY' },
  { id: 'jasper', name: 'Jasper', valuation: '$1.5B', founded: '2021', location: 'Austin, TX' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'gpt4',
    name: 'ChatGPT (GPT-4)',
    companyId: 'openai',
    logoUrl: 'https://picsum.photos/id/1/200/200',
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'A conversational AI model capable of understanding and generating natural language code, and more.',
    features: ['Multi-modal capabilities', 'Code generation', 'Data analysis', 'Web browsing'],
    website: 'https://chat.openai.com',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2023-03-14',
    lastUpdate: '2024-05-13',
    metrics: { totalUsers: 180000000, mau: 100000000, rating: 4.8, growthRate: 15 },
    tags: ['LLM', 'Chatbot', 'API Available']
  },
  {
    id: 'gemini',
    name: 'Gemini',
    companyId: 'google',
    logoUrl: 'https://picsum.photos/id/2/200/200',
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'Google’s most capable and general model, built to be multimodal from the ground up.',
    features: ['Native Multimodal', 'Large Context Window', 'Integration with Workspace'],
    website: 'https://gemini.google.com',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2023-12-06',
    lastUpdate: '2024-02-15',
    metrics: { totalUsers: 150000000, mau: 80000000, rating: 4.7, growthRate: 25 },
    tags: ['LLM', 'Multimodal', 'Google']
  },
  {
    id: 'claude3',
    name: 'Claude 3',
    companyId: 'anthropic',
    logoUrl: 'https://picsum.photos/id/3/200/200',
    category: 'Content Generation',
    subCategory: 'Text',
    description: 'A family of foundational AI models that sets new industry benchmarks on a wide range of cognitive tasks.',
    features: ['200K Context Window', 'Strong Reasoning', 'Steerability', 'Reduced Hallucinations'],
    website: 'https://claude.ai',
    pricing: ['Free', 'Paid', 'Enterprise'],
    launchDate: '2024-03-04',
    lastUpdate: '2024-04-01',
    metrics: { totalUsers: 25000000, mau: 10000000, rating: 4.8, growthRate: 40 },
    tags: ['LLM', 'Safety Focused', 'API Available']
  },
  {
    id: 'midjourney-v6',
    name: 'Midjourney v6',
    companyId: 'midjourney',
    logoUrl: 'https://picsum.photos/id/4/200/200',
    category: 'Content Generation',
    subCategory: 'Image',
    description: 'An independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    features: ['High Fidelity Images', 'Prompt Adherence', 'Text Rendering', 'Discord Interface'],
    website: 'https://midjourney.com',
    pricing: ['Paid'],
    launchDate: '2023-12-21',
    lastUpdate: '2024-01-15',
    metrics: { totalUsers: 16000000, mau: 5000000, rating: 4.9, growthRate: 10 },
    tags: ['Image Gen', 'Art', 'Discord']
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    companyId: 'microsoft',
    logoUrl: 'https://picsum.photos/id/5/200/200',
    category: 'Development',
    subCategory: 'Code',
    description: 'Your AI pair programmer. Copilot turns natural language prompts into coding suggestions.',
    features: ['Code Autocomplete', 'Chat Integration in IDE', 'Test Generation', 'Code Explanation'],
    website: 'https://github.com/features/copilot',
    pricing: ['Paid', 'Enterprise'],
    launchDate: '2021-06-29',
    lastUpdate: '2024-02-01',
    metrics: { totalUsers: 10000000, mau: 3000000, rating: 4.6, growthRate: 20 },
    tags: ['Coding', 'Productivity', 'VS Code']
  },
  {
    id: 'runway-gen2',
    name: 'Runway Gen-2',
    companyId: 'runway',
    logoUrl: 'https://picsum.photos/id/6/200/200',
    category: 'Content Generation',
    subCategory: 'Video',
    description: 'A multi-modal AI system that can generate novel videos with text, images, or video clips.',
    features: ['Text to Video', 'Image to Video', 'Motion Brush', 'Style Transfer'],
    website: 'https://runwayml.com',
    pricing: ['Freemium', 'Paid', 'Enterprise'],
    launchDate: '2023-03-20',
    lastUpdate: '2024-03-01',
    metrics: { totalUsers: 5000000, mau: 1000000, rating: 4.5, growthRate: 30 },
    tags: ['Video Gen', 'Creative Tools']
  },
  {
    id: 'jasper-ai',
    name: 'Jasper',
    companyId: 'jasper',
    logoUrl: 'https://picsum.photos/id/7/200/200',
    category: 'Marketing',
    subCategory: 'Copywriting',
    description: 'AI copilot for enterprise marketing teams to create on-brand content faster.',
    features: ['Brand Voice', 'Marketing Templates', 'SEO Mode', 'Campaign Management'],
    website: 'https://jasper.ai',
    pricing: ['Paid', 'Enterprise'],
    launchDate: '2021-01-15',
    lastUpdate: '2024-02-20',
    metrics: { totalUsers: 2000000, mau: 500000, rating: 4.4, growthRate: 5 },
    tags: ['Marketing', 'Writing', 'Business']
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    companyId: 'stability',
    logoUrl: 'https://picsum.photos/id/8/200/200',
    category: 'Content Generation',
    subCategory: 'Image',
    description: 'Latest open weights image generation model offering better photorealism.',
    features: ['Open Source Weights', 'High Resolution', 'Inpainting', 'Fine-tunable'],
    website: 'https://stability.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2023-07-26',
    lastUpdate: '2024-04-10',
    metrics: { totalUsers: 10000000, mau: 2000000, rating: 4.7, growthRate: 12 },
    tags: ['Open Source', 'Image Gen']
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    companyId: 'perplexity',
    logoUrl: 'https://picsum.photos/id/9/200/200',
    category: 'Productivity',
    subCategory: 'Writing Assistant',
    description: 'An AI-powered answer engine that cites sources and provides real-time information.',
    features: ['Real-time Search', 'Citations', 'File Upload Analysis', 'Pro Search'],
    website: 'https://perplexity.ai',
    pricing: ['Free', 'Paid'],
    launchDate: '2022-12-01',
    lastUpdate: '2024-05-01',
    metrics: { totalUsers: 10000000, mau: 4000000, rating: 4.8, growthRate: 150 },
    tags: ['Search', 'Research', 'Citations']
  },
  {
    id: 'sora',
    name: 'Sora',
    companyId: 'openai',
    logoUrl: 'https://picsum.photos/id/10/200/200',
    category: 'Content Generation',
    subCategory: 'Video',
    description: 'An AI model that can create realistic and imaginative scenes from text instructions.',
    features: ['60s Video Generation', 'Complex Camera Motion', 'Multiple Characters', 'High Fidelity'],
    website: 'https://openai.com/sora',
    pricing: ['Enterprise'], // Assuming limited release
    launchDate: '2024-02-15',
    lastUpdate: '2024-02-15',
    metrics: { totalUsers: 100000, mau: 50000, rating: 4.9, growthRate: 500 },
    tags: ['Video', 'Simulation', 'Beta']
  }
];
