'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Product } from '../types';
import { getProductAnalysis } from '../services/geminiService';
import { Sparkles, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface ProductAnalysisSectionProps {
    product: Product;
}

export default function ProductAnalysisSection({ product }: ProductAnalysisSectionProps) {
    const [analysis, setAnalysis] = useState<string | null>(null);
    const [loadingAnalysis, setLoadingAnalysis] = useState(false);
    const analysisRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (analysis && analysisRef.current) {
            analysisRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }, [analysis]);

    const handleAnalyze = async () => {
        setLoadingAnalysis(true);
        const result = await getProductAnalysis(product);
        setAnalysis(result);
        setLoadingAnalysis(false);
    };

    return (
        <section className="bg-primary-50 dark:bg-primary-900/10 rounded-2xl p-8 border border-primary-100 dark:border-primary-800 mb-8 shadow-sm">
            <div className="flex flex-col sm:flex-row items-center justify-between mb-6 gap-4">
                <h3 className="text-xl font-bold text-primary-900 dark:text-primary-100 flex items-center">
                    <Sparkles className="w-6 h-6 mr-3 text-primary-600 dark:text-primary-400" />
                    AI Strategic Analysis
                </h3>
                {!analysis && !loadingAnalysis && (
                    <button
                        onClick={handleAnalyze}
                        className="px-6 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-xl text-sm font-bold transition-all shadow-md hover:shadow-lg flex items-center transform hover:-translate-y-0.5"
                    >
                        <Sparkles className="w-5 h-5 mr-2" />
                        Generate Analysis
                    </button>
                )}
            </div>

            {loadingAnalysis && (
                <div className="flex flex-col items-center justify-center py-12 text-primary-600 dark:text-primary-400">
                    <Loader2 className="w-10 h-10 animate-spin mb-4" />
                    <span className="font-medium">Analyzing {product.name} market fit and capabilities...</span>
                </div>
            )}

            {analysis && (
                <div className="prose prose-lg dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 bg-white dark:bg-dark-800 p-6 rounded-xl border border-gray-100 dark:border-gray-700 shadow-inner">
                    <ReactMarkdown>{analysis}</ReactMarkdown>
                </div>
            )}

            {!analysis && !loadingAnalysis && (
                <p className="text-base text-primary-700 dark:text-primary-300 opacity-80 text-center sm:text-left max-w-2xl">
                    Unlock real-time strategic insights generated by Gemini AI. Discover hidden pros/cons, ideal user personas, and competitive advantages.
                </p>
            )}
            <div ref={analysisRef} />
        </section>
    );
}
